---
title: "pyro.indicator.species.oct28.2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(indicspecies)
```

```{r}
set.seed(30)

##trying with indval.g - date --> but I only want the burnt microplots 
#master.phylo.burn<-subset_samples(master.phylo, burn.status != "Unburnt")
#meta.data.microplots.burn<-sample_data(master.phylo.burn)
#var2<-meta.data.microplots.burn$sample_date
#indic.date<-multipatt(as.matrix(psotu2veg(master.phylo.burn)),var2, func = "indval.g", control = how(nperm = 999))
#summary(indic.date)

meta.data.microplots<-sample_data(master.phylo.2.lp)
meta.data.microplots
var2<-meta.data.microplots$Severity

##trying with indval.g - sev
indic.sev<-multipatt(as.matrix(psotu2veg(master.phylo.2.lp)),var2, func = "indval.g", control = how(nperm = 999))
summary(indic.sev)


##to seperate out the effects of severity on sample data I could try a date indicatros species for each severity level.

unburnt.phylo<-subset_samples(master.phylo.2.lp, Severity == "Unburnt")
meta.data.microplots.unburnt<-sample_data(unburnt.phylo)
low.phylo<-subset_samples(master.phylo.2.lp, Severity == "Low")
meta.data.microplots.low<-sample_data(low.phylo)
med.phylo<-subset_samples(master.phylo.2.lp, Severity == "Medium")
meta.data.microplots.med<-sample_data(med.phylo)
medsev.phylo<-subset_samples(master.phylo.2.lp, Severity == "Medium-Severe")
meta.data.microplots.medsev<-sample_data(medsev.phylo)
sev.phylo<-subset_samples(master.phylo.2.lp, Severity == "Severe")
meta.data.microplots.sev<-sample_data(sev.phylo)


var2<-meta.data.microplots.unburnt$sample_date

indic.date.unburnt<-multipatt(as.matrix(psotu2veg(unburnt.phylo)),var2, func = "indval.g", control = how(nperm = 999))

var2<-meta.data.microplots.low$sample_date

indic.date.low<-multipatt(as.matrix(psotu2veg(low.phylo)),var2, func = "indval.g", control = how(nperm = 999))

var2<-meta.data.microplots.med$sample_date

indic.date.med<-multipatt(as.matrix(psotu2veg(med.phylo)),var2, func = "indval.g", control = how(nperm = 999))

var2<-meta.data.microplots.medsev$sample_date

indic.date.medsev<-multipatt(as.matrix(psotu2veg(medsev.phylo)),var2, func = "indval.g", control = how(nperm = 999))

var2<-meta.data.microplots.sev$sample_date

indic.date.sev<-multipatt(as.matrix(psotu2veg(sev.phylo)),var2, func = "indval.g", control = how(nperm = 999))

summary(indic.date.unburnt)
summary(indic.date.low)
summary(indic.date.med)
summary(indic.date.medsev)
summary(indic.date.sev)



```

